<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Soflomo\Sitemap\Module'                       => __DIR__ . '/Module.php',
    'Soflomo\Sitemap\Controller\SitemapController' => __DIR__ . '/src/Soflomo/Sitemap/Controller/SitemapController.php',
);
