<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sitemap\Module'                       => __DIR__ . '/Module.php',
    'Sitemap\Controller\SitemapController' => __DIR__ . '/src/Sitemap/Controller/SitemapController.php',
);
